@echo off
echo Installing bcryptjs...
npm install bcryptjs
echo Installing @prisma/client...
npm install @prisma/client
echo Generating prisma client...
npx prisma generate
echo Pushing schema to DB...
npx prisma db push
echo Done!
